# Utilise une image Python officielle
FROM python:3.10-slim

# Crée et utilise un dossier pour l'app
WORKDIR /app

# Copie uniquement le requirements.txt d'abord (meilleure gestion du cache)
COPY backend/requirements.txt .

# Installe les dépendances
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Puis copie tout le reste du code backend
COPY backend/ .

# Expose le port FastAPI
EXPOSE 8000

# Lance l'application FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]