# Utilise une image Python officielle
FROM python:3.10-slim

# Crée et utilise un dossier pour l'app
WORKDIR /app

# Copie les fichiers dans le conteneur
COPY . .

# Installe les dépendances
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Expose le port FastAPI
EXPOSE 8000

# Lance l'application FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]