name: CI - Test et Build

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name:  Cloner le dépôt
      uses: actions/checkout@v3

    - name:  Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name:  Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name:  Lancer les tests
      run: |
        pytest backend/tests/

    - name:  Build Docker image
      run: |
        docker build -t myapi:latest -f backend/Dockerfile .