name: Test simple2

on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Run echo
      run: echo "GitHub Actions fonctionne !"
